spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12826312
spring.datasource.username=sql12826312
spring.datasource.password=dnEv2CvE3q

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

server.port=8080